### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by david-hordon**
Fellow collaborators! Your comments on my edits to the README. Do I have your support in merging to master?

### CODE REVIEW

**Comment by CHKass** [comment]
Yes, indeed dear fellow, do feel free to merge.

**Comment by david-hordon** [comment]
I've had a change of heart, and now think this repo should be entirely free of any political persuasion. I suggest we limit ourselves to the following topics:

- HTML
- CSS
- Terminal
- Git
- GitHub
- GitHub Desktop

What say my fellow collaborators?

**Comment by CHKass** [comment]
Yes, I agree, but it is a bit like limiting ourselves to _everything we do!_
I'm beginning to get the hang of this.

**Comment by david-hordon** [comment]
### The Value of Comments
At the moment we're just discussing the README edits. But imagine we were styling the &lt;nav&gt; tag to the website. We'd be using these comments to suggest changes to each other's HTML and CSS choices, perhaps even creating a branch of the branch to demonstrate. That, I think, would reveal the real point about the **comment**.

**Comment by CHKass** [comment]
I see now that the email alert notifying me of your comment included the complete comment in the email. Which is useful so I can judge how urgent it is to respond – which could just as easily be by email.

**Comment by david-hordon** [comment]
There's a record of everything we do in the History of this repo, including all the comments made. If your computer blew up, you could reclaim that History anytime.

**Pull request merged**
